### ISSUE TITLE
FIT field name should not be translated

### ISSUE THREAD

**Issue by flocsy** [wwarby/walker#10]
The 1st parameter of createField is name, however that should not be translated IMHO. I imported my Garmin data to runalyze.com and there I can see the data recorded by walker, and when I did a test and my watch was set to Hebrew it added fields like:
מספר_צעדים_הממוצע_לשעה
and
צעדים
which are "Steps / Hour" and "Steps" respectively.
However it makes no sense to have these translated. This is pure data, not really displayed to the user, and in fact I would argue that it actually is worse to translate it than to have it in English. I think you should only use the translations in fit-contributions.xml. (BTW this will even free a few bytes of code) which then is used in GCM, web to translate the labels.

The same is true for the units.

BTW I would even remove the ", :units => stepsUnits" part (I did that in my app, because when you don't set it then in GCM and web you'll see the proper translation set in fit-contributions.xml, the con is that then you don't see it in places like runalyze.com)

**Comment by wwarby** [comment]
Right, so a couple of things on this.

On the first parameter to `createField()` this value definitely **does** get displayed to the user, in the Garmin Connect App (see screenshot below). You're right that it is technically pure data (a theoretically internal field name), but Garmin provides no way of defining a display label for the field name in the Garmin Connect app and plonks this internal field name on screen in the app.

So whilst I concede that it would be more useful to have a consistent field name that is unaffected by device language _if you happen to be uploading your FIT data to a third party website that can make use of third party FIT contributions_, I'd argue that changing this to a something like `stepsPerHour` regardless of language would make the presentation uglier and less readable in the Garmin Connect App, especially for non-English speakers. So it comes down to a judgement - how many users of a casual walking app are uploading their FIT data to third party apps, vs how many people are only ever looking at the data in the Garmin Connect app. I suspect (though I have no data to back this up) that it is overwhelmingly more common that people look at the data in Garmin Connect and nowhere else, and for that reason I'm inclined to keep it as it is.

With regards to the units, I'm not sure I've fully grasped your point, but the [documentation](https://developer.garmin.com/connect-iq/api-docs/Toybox/ActivityRecording/Session.html#createField-instance_function) does state for this value specifically that `This should use the current device language`. Surely if I removed it, I just wouldn't see the word "steps" (or the relevant translation) in the Garmin Connect app?

![Screenshot](https://user-images.githubusercontent.com/6769065/175035850-16b5fbe5-6134-49ee-bd47-e960ec398f53.jpg)

**Comment by flocsy** [comment]
all the strings in the red circle and "steps" (unit) are displayed in GCM according to the strings in the fitcontribution.xm and they are translated according to the language of the android where GCM runs. So for this you shouldn't worry. When you export it to a 3rd party app then you'll see the string that you set in the code, and then you can argue what makes more sense.

The 1st parameter in createField is not displayed anywhere in Garmin, that too you'll only see when you export it to 3rd party. I started with full names like "avg_lap_heart_rate", but since I had 7 fields it was lot of bytes in the code, so I changed them to much shorter acronyms. Though I admit if it's exported then it helps if it's a bit more readable. Maybe it's worth to test how many bytes the code for WatchUi.loadResource(Rez.Strings.foo) + the reference in the Strings table adds to the memory footprint and decide accordingly if it's worth to use the loadResource (with or without actually translating the string or just use it for shortening the memory footprint and keep it in the default language only) or just hard-code some english field name like avg_lap_heart_rate.
