### ISSUE TITLE
I used walker‘s UI with modification in my app？Is it OK？

### ISSUE THREAD

**Issue by Likenttt** [wwarby/walker#2]
Hi, wwarby， your datafield is really powerful and elegant. I reuse its UI design and drawing code with modification in my app JumpJump(https://apps.garmin.com/en-US/apps/dc6ceca8-6ec6-49f2-b711-4ebc0d347177?tab=reviews&displayCurrentVersion=true). I have declared the UI is inspired by yours with a link to Walker in the description. Is it ok?

**Comment by Likenttt** [comment]
![945lte-screenshot](https://user-images.githubusercontent.com/26034018/122663632-ae241300-d1ce-11eb-845f-710183e31493.png)

**Comment by Likenttt** [comment]
![JumpJumps-usages-en](https://user-images.githubusercontent.com/26034018/122663786-808b9980-d1cf-11eb-861e-0675a61e2697.png)

**Comment by wwarby** [comment]
Hi Chuanyi,

That’s absolutely fine, I published the project as open source software in the hope it would help other developers and I'm really glad to see it taking on new life for a new app :)

I’ve just pushed out an update with your changes to the Chinese translation too.

Thanks again!

**Comment by Likenttt** [comment]
Hi Wwarby,
I noticed a phenomenon, many Chinese Connect IQ users refuse to download an app with an English description although the author has internationalized their apps because they don't know about English, in which case walker has fewer downloads (comparing to app.garmin.com )in apps.garmin.cn . The first impression keeps them out of doors.
A small suggestion: translate the description from English to other languages.
