### ISSUE TITLE
Laps steps

### ISSUE THREAD

**Issue by eversonl** [wwarby/walker#6]
Hi, I believe walker is mean to also show steps per lap, is this correct as a body seem to get that information.

**Comment by wwarby** [comment]
Hi @eversonl. It doesn't measure steps per lap I'm afraid. On screen, it only shows two step-related values: the total number of steps for the day, and the total for the activity. In the metadata that it collects and inserts into the FIT file (which ends up viewable in the activity stats in Garmin Connect) it will average capture steps per KM (or steps per mile if your watch is configured to use imperial units), which is potentially the same thing as steps per lap if you are using auto-laps with a lap interval set to 1 KM (or 1 mile) - but I've never specifically put steps per lap in as a feature, and don't particularly intend to I'm afraid.
