### ISSUE TITLE
Resuming activity starts counting steps from 0

### ISSUE THREAD

**Issue by flocsy** [wwarby/walker#8]
When I stopped a Hike activity, chose "resume later" and later resumed it the time, distance fields displayed the correct data since the beginning of the track, however the steps started counting again from 0

**Comment by wwarby** [comment]
As mentioned on #7 I think this is the root cause of the screwy numbers you're seeing in step metrics for the hike. I need to figure out why I'm losing the step count when the activity is resumed.

**Comment by ffes** [comment]
It is not just the Hike activity, I run into the same problem with a Walking activity as well

**Comment by wwarby** [comment]
Yeah, I thought that would be the case - Walker doesn't really know or care which activity type you're using so it stands to reason it would happen in both. I will get to this I promise - just got a lot going on at the moment ;)

**Comment by wwarby** [comment]
I've solved this (I think). The fix was relatively simple, but I won't tell you how many times I had to pace up and down my kitchen stopping and starting my watch with between plugging it in to view debug logs before I had a solid grasp of the problem!

Releasing the fix shortly.
