### ISSUE TITLE
Optimize DataQueue.average

### ISSUE THREAD

**Issue by flocsy** [wwarby/walker#9]
Since you always call heartRateData.add and then immediately heartRateData.average, I think you should delete the code in DataQueue.average and instead add a new field: average, that is maintained by add and reset and average() only returns it:

add(element) {
    var oldestVal = data[pos];
    if (oldestVal != null) {
        average -= oldestVal;
    }
   data[pos] = element;
   average += element;
   pos = (pos + 1) % maxSize;
}

**Comment by wwarby** [comment]
I've integrated this suggestion, thanks 👍
